### ISSUE TITLE
Avoid replacing selected text

### ISSUE THREAD

**Issue by Solnaes** [zolrath/obsidian-auto-link-title#10]
Hey! Great plugin!

 I am using "Paste URL into selection" Obsidian plugin, and I would like to use this plugin in conjunction with it. However "Auto Link Title" replaces selected text, and seems to overwrite the behaviour of the other application. Could you consider changing this behaviour for selected/highlighted text? 

Link to the mentioned plugin:
https://github.com/denolehov/obsidian-url-into-selection

**Comment by zolrath** [comment]
Thanks! Hm, I could add an option to disable the plugin when text is selected.
Thanks for the heads up!

**Comment by wongFanx** [comment]
Same question. Wish to add a shortcut key, which will disable the plug-in when pasting.

**Comment by EKliptus** [comment]
I need this feature too ! Thanks, good job !

**Comment by zolrath** [comment]
This setting has been merged and released!
