### ISSUE TITLE
Pasting links on iphone doesn't work on the last version

### ISSUE THREAD

**Issue by milxone** [zolrath/obsidian-auto-link-title#100]
Iphone 14 pro
Doesn't work when copy-pasting
Doesn't work when enhancing the link in Obsidian

**Comment by WereWolfPL** [comment]
Same thing with Android (14 in my case). I think it might be the profile with all mobile versions after the last update, not specific to Android or iPhone, but it's only my guess.

**Comment by milxone** [comment]
Yeah, the plugin uses different method to fetch link title. On Mac it works as expected.

**Comment by FeralFlora** [comment]
Not working on my iPad either (iPadOS 17.2, Obsidian v. 1.4.17).

**Comment by zolrath** [comment]
Hm, I'll need to check if the API we've switched two is just not available on the mobile devices or what the issue here is.
I'll likely end up adding the previous method as a fallback if the API does not exist.
I'll be able to dig in this weekend!

**Comment by zolrath** [comment]
I've moved the new scraper behind an option in Settings.
Seems it works well on desktop but not mobile, more investigation needed but this should let it work on your phone again!
