### ISSUE TITLE
Pasting links on Android still doesn't work (since 1.5.0 update).

### ISSUE THREAD

**Issue by WereWolfPL** [zolrath/obsidian-auto-link-title#102]
The previous issue has been closed, so I'm not sure if it shows the replies, that's why I'm opening it again.

Actually, the new update (1.5.2) didn't help with Android, still doesn't paste anything at all.

I did manage to run developer console for android, here's the error when I try to paste a link to obsidian, maybe it'll help you somehow. It's the same error regardless of the new option enabled or disabled.
Below is the log with the error from the console.
[localhost-1705223419935.log](https://github.com/zolrath/obsidian-auto-link-title/files/13930906/localhost-1705223419935.log)

**Comment by zolrath** [comment]
Thank you very much for the log!
Looks like the crypto module doesn't work on Android so I've reverted back to my old manual method of generating the hash.
Can you confirm that the new version fixes it for you?

**Comment by WereWolfPL** [comment]
Now it works. The new scraper method shows "site unreachable", but with this option turned off it works perfectly, thanks :)

**Comment by Matgoeth** [comment]
Tested and works fine with the "legacy" method, thank you for update, @zolrath !
Super keen on testing crypto module someday if you'd like to fix it someday for mobile (on PC it works great!)

**Comment by zolrath** [comment]
Glad to hear it works, and a bummer to hear that the new scraping method is also unavailable on mobile as it's an Obsidian API, was hoping it would work on all devices.

Thanks for the confirmation!
