### ISSUE TITLE
Feature request: Allow login to fetch titles from private sites

### ISSUE THREAD

**Issue by Martin-Milbradt** [zolrath/obsidian-auto-link-title#114]
Examples:
- Google
- Facebook

**Comment by faoiseamh** [comment]
Would love this as well. I paste lots of links to project management tools that require authentication to fetch appropriate titles for, which would be very helpful. Perhaps it could allow you to share authenticate browser session cookies or something like that?

**Comment by jeffmadison** [comment]
I get around this by using the Custom Frames plugin. I create a frame for each of the protected sites I use frequently, and once I log into the site within that frame, the auth cookie gets saved within the browser context within Obsidian (or something like that). After that, whenever I paste a URL, that auth cookie automatically gets sent when this plug-in is looking up the page title.

The only bummer is that those cookies expire, then I have to re-open the Custom Frame and log in again. It would be nice if obsidian-auto-link-title could integrate with Custom Frames such that it would automatically open up whichever Custom Frame has a URL that matches the link it is trying to look up when it encounters an HTTP 401 or redirect.

**Comment by jjspace** [comment]
This was marked as fixed in #128 but I do not believe that to be the case. As far as I understand there's nothing the [LinkPreview API](https://docs.linkpreview.net/) does to get around pages requiring authentication. Even from their own docs:
> Some of the reasons for the failed, blank, or incomplete API response are beyond our control:
> 
> - Private pages or pages that require authentication or login

Similar to @faoiseamh I was hoping to use this for GitHub issue links for private repos but those are still not working (as I'd expect reading the docs). I assume something like the custom frames plugin is needed unless there's a service like the LinkPreview API that _does_ allow authenticating with external services.

CC @zolrath, probably worth re-opening this

**Comment by felixsdys** [comment]
> I get around this by using the Custom Frames plugin. I create a frame for each of the protected sites I use frequently, and once I log into the site within that frame, the auth cookie gets saved within the browser context within Obsidian (or something like that). After that, whenever I paste a URL, that auth cookie automatically gets sent when this plug-in is looking up the page title.
> 
> The only bummer is that those cookies expire, then I have to re-open the Custom Frame and log in again. It would be nice if obsidian-auto-link-title could integrate with Custom Frames such that it would automatically open up whichever Custom Frame has a URL that matches the link it is trying to look up when it encounters an HTTP 401 or redirect.

Does the workround still work now? I used to use custom-frames along with auto-link-title to fetch titles from private sites, but after recent updates I found it does not work anymore.

I think the workaround now breaks @zolrath

**Comment by jeffmadison2** [comment]
> > I get around this by using the Custom Frames plugin. I create a frame for each of the protected sites I use frequently, and once I log into the site within that frame, the auth cookie gets saved within the browser context within Obsidian (or something like that). After that, whenever I paste a URL, that auth cookie automatically gets sent when this plug-in is looking up the page title.
> > The only bummer is that those cookies expire, then I have to re-open the Custom Frame and log in again. It would be nice if obsidian-auto-link-title could integrate with Custom Frames such that it would automatically open up whichever Custom Frame has a URL that matches the link it is trying to look up when it encounters an HTTP 401 or redirect.
> 
> Does the workround still work now? I used to use custom-frames along with auto-link-title to fetch titles from private sites, but after recent updates I found it does not work anymore.
> 
> I think the workaround now breaks [@zolrath](https://github.com/zolrath)

It seems to still be working for me. 🤷
