### ISSUE TITLE
Fetch Reddit link title

### ISSUE THREAD

**Issue by lomafor** [zolrath/obsidian-auto-link-title#119]
it's a problem with Reddit, the title is always "Reddit - Dive into anything" with auto fetch. 

is there a way to fix it? thank you!

**Comment by JamesSagauinit** [comment]
not really a solution, but the plugin works fine on [old.reddit.com](old.reddit.com)

**Comment by albertoloscerritos** [comment]
Me too. It was working all right until like a week ago :(
