### ISSUE TITLE
Escape the vertical bar "|" to avoid breaking tables

### ISSUE THREAD

**Issue by mjvar** [zolrath/obsidian-auto-link-title#123]
Pasting links into Obsidian tables with this plugin active can sometimes break the table. If the link title contains the vertical bar character |, the table parser will interpret that as a cell division. This will break up the link into 2 cells and add an extra column.

To avoid this, I propose automatically escaping the | character with a backslash when it appears in the link title like so: \\|. This will prevent the Obsidian table renderer from reading the | as a cell division. The first image shows what escaping the bar looks like (expected behavior), while the second image shows what happens when the bar is not escaped (current behavior).

![image](https://github.com/user-attachments/assets/5caf096e-2100-42af-8f3d-7d01d9fc089f)

![image](https://github.com/user-attachments/assets/0ce851e7-ca38-4ba8-9be7-0747f01c12fd)

**Comment by bfcns** [comment]
Seems like this already been applied. But the problem is it divides the link in obsidian.

Maybe there should be 2 states to paste? into table and not?

**Comment by zolrath** [comment]
Hm, can you show me an example of what you mean by dividing the link in obsidian? Both in source and rendered view.

**Comment by bfcns** [comment]
Seems like it only happens in live and source mode, not in reading mode. Below the images highlights part of the links in hover. First one is source mode, second one is live, all of them is highlighted in reading mode. Maybe it is not an issue, I don't know.
![Screenshot 2024-12-19 082339](https://github.com/user-attachments/assets/15614757-1145-4751-93f2-b8461b7527c8)
![Screenshot 2024-12-19 082438](https://github.com/user-attachments/assets/55621ae7-7cbf-4b3e-8b97-8a749e016afd)
