### ISSUE TITLE
Pasting Youtube link results only in title "YouTube"

### ISSUE THREAD

**Issue by HighTML** [zolrath/obsidian-auto-link-title#124]
It would be nice if it could fetch the video title and append it to "YouTube -"

I'm on iOS Obsidian 1.6.7 (149), using plugin 1.5.4

**Comment by qianxun321** [comment]
Same issue on mac.

**Comment by albertoloscerritos** [comment]
same here, YouTube links no longer showing the title

**Comment by illusoryemotion** [comment]
This doesn't work if not using the LinkPreview API, so by default it is still an issue for anyone using the Android app who hasn't taken extra steps to get an API key
