### ISSUE TITLE
Wrong title being pasted when fetching multiple titles at once

### ISSUE THREAD

**Issue by stephanfuchs** [zolrath/obsidian-auto-link-title#14]
I've tried to fetch one url title before another fetch was done, which resulted in both titles being the same and hence one title being wrong.

**Comment by zolrath** [comment]
Hm, this used to work, I'm in a bit of crunch time at the moment but I'll check into this as soon as I can!

**Comment by heliostatic** [comment]
Came here to file the same issue -- noticed it in particular with the "enrich existing url" feature.

**Comment by jamiekowalski** [comment]
@zolrath I have an example fix for this [here](https://github.com/jamiekowalski/obsidian-auto-link-title/commit/16fe47d5dc49a44097637116ab1e1de84377fbaf). If I get around to cleaning it up, I'll submit a pull request.
