### ISSUE TITLE
Editing name manually bug

### ISSUE THREAD

**Issue by gchegr** [zolrath/obsidian-auto-link-title#18]
Fetching of some titles works slowly for.
At several particular sites I store links from this process takes enough time for me to go to the page, copy the link name I need, return to Obsidian and paste it instead of 'fetching code' manually. And when the plugin does finally insert the fetched name, it gets pasted in the beginning of my note — because there is no more code to be replaced by it (and generally I do not like the name pattern that this site uses and will replace the name anyway).
So, please:
1. https://github.com/zolrath/obsidian-auto-link-title/issues/6 — this would have solved my issue
2. Do not paste the name when there is no code found in the note :)
Thus said, I love the plugin very much, because when it works — it works, and saves time.

**Comment by zolrath** [comment]
That PR has been merged and if you change the name before it returns it will no longer insert the name at the start of the note!
