### ISSUE TITLE
Takes over Ctrl+v

### ISSUE THREAD

**Issue by jacobmercy** [zolrath/obsidian-auto-link-title#19]
Have a weird issue where plugin replaces my regular ctrl+v pastes. Have tried changing the keyboard shortcut, restarting, uninstalling. Using Windows v0.12.12.

**Comment by zolrath** [comment]
I've added a new setting in the latest release which allows you to disable the plugins standard handling of ctrl+v pastes. It also exposes a new hotkey which you can bind to whatever you'd like to paste using Auto Link Title!
