### ISSUE TITLE
Tweet urls just say "Twitter" as title, should show full text of tweet

### ISSUE THREAD

**Issue by bjornfiles** [zolrath/obsidian-auto-link-title#22]
Fantastically useful plug-in, but would be that much more so if it auto-inserted tweet body text of Twitter urls.

**Comment by zolrath** [comment]
Ah, that would be an interesting special case. In the coming weeks I should have a bit more time to dedicate back into the plugin I'll consider this!

**Comment by leowill01** [comment]
Great plugin! But yeah, pasting links to tweets doesn't work. For me it just puts the URL of the link as the link title, no easy to read title, even though I can see the webpage title of the tweet on my safari tab as `User Name on Twitter: "This is the text of the tweet"`, which is what I expected this plugin to put as the link title when pasted. Any progress on this?

**Comment by zolrath** [comment]
Unfortunately, twitter adds that information in after an API request post-load and returns different results when fetched. I'll look into using a different method for specific sites at a future date which should allow us to better handle specific sites.

**Comment by NomarCub** [comment]
Having closed this, is there an issue to track site-specific fixes like this?
