### ISSUE TITLE
Trim white space characters from both ends of the title

### ISSUE THREAD

**Issue by claremacrae** [zolrath/obsidian-auto-link-title#24]
Thank you for a super useful plugin...

I've had a few cases recently where whitespace characters have ended up at the start or end of the titles, and I trim them by hand.

It's not a big deal, but I wondered if it would be possible for the plugin to remove them automatically. I can't think of any situation where they would be useful.

Examples, as generated by the plugin:

- [\n    Archives | CSS-Tricks](https://css-tricks.com/archives/)
- [\r\n\tHoliday at Nicolle Tower in St Clement, Jersey | The Landmark Trust\r\n](https://www.landmarktrust.org.uk/search-and-book/properties/nicolle-tower-9638/#Overview)

Source of the above links:

```
- [\n    Archives | CSS-Tricks](https://css-tricks.com/archives/)
- [\r\n\tHoliday at Nicolle Tower in St Clement, Jersey | The Landmark Trust\r\n](https://www.landmarktrust.org.uk/search-and-book/properties/nicolle-tower-9638/#Overview)
```

**Comment by zolrath** [comment]
#26 Solved this issue and has been merged!

**Comment by claremacrae** [comment]
Thank you very much!
