### ISSUE TITLE
Fail on Recognizing URLs Containing Specific Strings

### ISSUE THREAD

**Issue by tswwe** [zolrath/obsidian-auto-link-title#30]
Hi, I noticed that this plugin will miss a URL if it has a string like 'ai' in the middle of it. For example:
* it goes well with this one: `https://www.a.com`
* but this one will be missed: `https://www.ai.com`

After skimming through the code, I think this problem has something to do with the regex expression matching image files. Later I will submit a PR to try to fix it, but I am not sure whether it would introduce any new problem. Feel free to reject the PR if anything gets worse.

**Comment by zolrath** [comment]
Good catch! Definitely a regex improvement. Merged!
