### ISSUE TITLE
Titles are mixed when two or more links are being fetched

### ISSUE THREAD

**Issue by knwng** [zolrath/obsidian-auto-link-title#33]
Hi everyone, I'm a obsidian user from China and I really appreciate this useful plugin. However, as you may know, the network connections to some specific websites are not quite good here, so I have to wait for the titles.

I noticed that if there're two or more links are in fetching stages, they'll finally get the same title as the one fetched early. For example, I'm fetching the titles of a.example.org and b.example.org, and if the title of a.example.org arrives first, both of the titles will be that one. I think some sort of isolation mechanism will help. Again, thank you for developing this awesome plugin!

**Comment by zolrath** [comment]
This should be corrected, let me know if this is still happening to you!
