### ISSUE TITLE
Google Doc titles

### ISSUE THREAD

**Issue by kmaustral** [zolrath/obsidian-auto-link-title#38]
This plugin helps greatly make Obsidian a more readable platform. 

Currently, Google Docs links are giving the generic title: "Google Docs – create and edit documents online, for free"

It would be great to pull the document title. Most clippers are able to do that. 

Much appreciated.

**Comment by kmaustral** [comment]
This seems to have been fixed now. It may have been an issue with the connection.

**Comment by mbseid** [comment]
I really wish this plugin had this capability. It would be great to be able use Google OAuth to get a token and use that in the request. I'm not sure how it would work in practice but that basic premise could work on other sites too.
