### ISSUE TITLE
Unrecognized link exists

### ISSUE THREAD

**Issue by wongFanx** [zolrath/obsidian-auto-link-title#4]
Unrecognized link exists:

- https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=2&tn=baiduhome_pg&wd=%E5%9B%BE%E4%B9%A6%E9%A6%86%E5%AD%A6%20%E7%9B%AE%E5%BD%95%E5%AD%A6&rsv_spt=1&oq=%25E5%259B%25BE%25E4%25B9%25A6%25E9%25A6%2586%25E5%25AD%25A6%2520%25E7%259B%25AE%25E5%25BD%2595%25E5%25AD%25A6&rsv_pq=d6a17b45004bb85c&rsv_t=da48%2FEdrpDzRCX4U%2FKfES3gAkctP1zYS5Hdgla3yIR3iowtsabAc%2BYAo%2BnF6y%2FulfB9Z&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t
- https://www.baidu.com/s?wd=%E4%BD%A0%E7%9A%84%E5%90%8D%E5%AD%97

**Comment by wongFanx** [comment]
In addition, after adding an identifiable link behind an unrecognizable link, an error with the same name will occur.
![image](https://user-images.githubusercontent.com/14831158/115967503-7ea5b100-a565-11eb-9dcd-b186c4895590.png)

**Comment by zolrath** [comment]
Thanks for the links! Fixed in next version:
```
[百度一下，你就知道](https://www.baidu.com/)
[图书馆学 目录学_百度搜索](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=2&tn=baiduhome_pg&wd=%E5%9B%BE%E4%B9%A6%E9%A6%86%E5%AD%A6%20%E7%9B%AE%E5%BD%95%E5%AD%A6&rsv_spt=1&oq=%25E5%259B%25BE%25E4%25B9%25A6%25E9%25A6%2586%25E5%25AD%25A6%2520%25E7%259B%25AE%25E5%25BD%2595%25E5%25AD%25A6&rsv_pq=d6a17b45004bb85c&rsv_t=da48%2FEdrpDzRCX4U%2FKfES3gAkctP1zYS5Hdgla3yIR3iowtsabAc%2BYAo%2BnF6y%2FulfB9Z&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t)
[你的名字_百度搜索](https://www.baidu.com/s?wd=%E4%BD%A0%E7%9A%84%E5%90%8D%E5%AD%97)
```
and
```
[你的名字_百度搜索](https://www.baidu.com/s?wd=%E4%BD%A0%E7%9A%84%E5%90%8D%E5%AD%97)
[弱点 (豆瓣)](https://movie.douban.com/subject/3552028/)
```

**Comment by wongFanx** [comment]
Amazing speed, thank you!
