### ISSUE TITLE
No title fetching on mobile

### ISSUE THREAD

**Issue by ahmetasabanci** [zolrath/obsidian-auto-link-title#41]
I've recently noticed that link paste action doesn't fully work on my Obsidian iOS version. I'm saying fully because whenever I paste a link, it's pasted with Markdown link formatting but there's no title fetching happens. Text part just stays blank. 

I've tried waiting and checking if there might be something else causing an issue but everything seems fine. I'm not sure if it's a mobile limitation or a bug but I'd like to have this plugin working as intended on my phone too.

**Comment by koenraijer** [comment]
I’m having the exact same problem.

**Comment by Calorion** [comment]
Do you have "Enhance Default Paste" on?

**Comment by grizzee** [comment]
I have the same problem. i paste a URL and it produces a Markdownlink with an empty Textfield. 
"Enhance Default Paste" is on.

I was very hopeful because that would have simplified the link insertion on mobile very much.

---
iOS 15.7.3
Obsidian 1.4.3
Auto Link Title 1.4.1

**Comment by timfong888** [comment]
Ditto. Read the docs which day to use tap and hold and it doesn't work. 

However when I use the ribbon it works.

**Comment by AndresProgrammer10** [comment]
https://github.com/zolrath/obsidian-auto-link-title/issues/46

at the same post
