### ISSUE TITLE
Link Titles on secure sites

### ISSUE THREAD

**Issue by gudstrand** [zolrath/obsidian-auto-link-title#42]
Anyway to configure this plugin to use auth? When working on secure pages (with Edge) the link titles fail since this plugin is not using the login cookie.

**Comment by wyne** [comment]
As mentioned here https://github.com/zolrath/obsidian-auto-link-title/issues/38#issuecomment-1184426611, you can use the [Custom Frames plugin](https://github.com/Ellpeck/ObsidianCustomFrames) to log in from obsidian, then the title can be fetched properly.

**Comment by zolrath** [comment]
I'll look into adding this as a specific feature in the future but right now it's not planned, sorry about that!
