### ISSUE TITLE
High CPU usage when can't fetch title

### ISSUE THREAD

**Issue by bogdaba** [zolrath/obsidian-auto-link-title#44]
Sometimes when pasting an URL the plugin is not able to fetch the title. The obsidian process that is created will continue to work until manually terminated. Single unfetched title adds around 8% CPU workload in my case.

Would be nice if process would kill itself automatically if it runs for more than few seconds

![NbUXZR0p4Q](https://user-images.githubusercontent.com/64439910/161404331-0c277c5a-b930-4d83-9ea2-e18e0d190e01.png)
![Obsidian_aEoSMf5sg1](https://user-images.githubusercontent.com/64439910/161404332-5cdc93c8-e24c-47f2-a1ed-a90ca012e926.png)

**Comment by zolrath** [comment]
This should be fixed with the new version - if it's not please let me know!
