### ISSUE TITLE
[feature request]  Exclude url list

### ISSUE THREAD

**Issue by kobakou** [zolrath/obsidian-auto-link-title#51]
Could you support exclude url list in option?
I often paste comapany internal url in .md, but auto-link-tilte can not reach and fetch the title.

**Comment by shap-po** [comment]
+1 some URLs (like TikTok) crash Obsidian, it would be great to have an option to exclude them

**Comment by ctapmex** [comment]
+1

**Comment by miguelfbrito** [comment]
+1
