### ISSUE TITLE
occasional occurrence of site unreachable problem.

### ISSUE THREAD

**Issue by tyePhDCandy** [zolrath/obsidian-auto-link-title#57]
**problem** : sometimes when my connection to certain web url is slow, it shows site unreachable. then, when the internet connection is better, it fetches the title correctly.

**possible solution**: increase the threshold maximum value for title fetching time.

**Comment by jas10101** [comment]
Hi, I am facing this problem always, no matter if the internet is fast or slow. **The problem started a few weeks ago I think.** Any idea how to fix it? My links now all show [Site unreachable] after pasting. The one which were pasted before the problem started are still showing normal.

**Comment by zolrath** [comment]
Hm, I just did some tests with the latest version and I'm not seeing any issues.

Can you double check that you're on the latest version? There was a release a few weeks ago that was up for a few hours that effectively always returned Site Unreachable.

If you can confirm you're on `1.4.1` and give me some example links that are failing I will look into it!

**Comment by jas10101** [comment]
Hey thank you so much! I just updated from 1.4.0 to 1.4.1 as you advised, and it fixed the issue! Thanks!

**Comment by zolrath** [comment]
Excellent! Glad to hear it.
