### ISSUE TITLE
cannot paste a link in memos if auto-link-title turns on.

### ISSUE THREAD

**Issue by zhilongjia** [zolrath/obsidian-auto-link-title#59]
I cannot paste a link in [memos](https://github.com/Quorafind/Obsidian-Memos) if auto-link-title turns on, but while can paste a link in memos if auto-link-title turns off. Thank you.

auto-link-title v1.2.5
obsidian appimage for Linux v1.1.9

**Comment by zolrath** [comment]
You should be able to paste links in memos now! It won't auto-link them within that plugin, but it won't stop your normal link pastes now!
