### ISSUE TITLE
Disable automatic title fetching

### ISSUE THREAD

**Issue by phumberdroz** [zolrath/obsidian-auto-link-title#6]
I would like to disable the automatic title fetching and only use the hotkey.

Is this already somehow possible? :)

**Comment by zolrath** [comment]
Hm, not at the moment but that seems like a great option to add, will do!

**Comment by rishifter** [comment]
May I suggest add another hotkey for pasting so we can, at the time of pasting choose whether to paste with title or normally.

**Comment by karbassi** [comment]
@zolrath how about <kbd>cmd/ctrl</kbd> + <kbd>v</kbd> for regular auto link titling and <kbd>shift</kbd> + <kbd>cmd/ctrl</kbd> + <kbd>v</kbd> for regular pasting (auto title fetching off)?

**Comment by mike2003** [comment]
I was also looking for such an opportunity here. But I found another plugin with command Convert a URL into markdown +Title Only mode

**Comment by karbassi** [comment]
> I was also looking for such an opportunity here. But I found another plugin with command Convert a URL into markdown +Title Only mode

What is the other plugin you found? Can you share a link please?

**Comment by mike2003** [comment]
https://i.imgur.com/nVZBbEr.jpg
Convert a URL into markdown

**Comment by Benature** [comment]
Same request. Sometimes I want to [paste URL into selection](https://github.com/denolehov/obsidian-url-into-selection), but not fetch title.

**Comment by wenlzhang** [comment]
It would be great to be to paste pure URLs with hot keys like `shift + cmd/ctrl + v`, as @karbassi suggested.

**Comment by mcndt** [comment]
+1 on this feature. I have had many moments where I had to manually delete the auto-fetched title because I only wanted the URL.

**Comment by feigaoxyz** [comment]
vote 👍

**Comment by Aaron-Bopp** [comment]
It would be great if there would be an option to paste normally with ctrl-shift-v and auto link the tile when you use ctrl-v

**Comment by zolrath** [comment]
I've added a new setting in the latest release which allows you to disable the plugins standard handling of ctrl+v pastes. It also exposes a new hotkey which you can bind to whatever you'd like to paste using Auto Link Title!
