### ISSUE TITLE
Site unreachable problem

### ISSUE THREAD

**Issue by TigBuh99** [zolrath/obsidian-auto-link-title#66]
I get a "Site unreachable" instead of the page title. This started today. The only significant change is that I have began using obsidian Sync, but I expect that it shouldn't be relevant. There is no problem with my Internet speed (which was a possible cause reported by someone earlier ).

**Comment by nhan000** [comment]
Same issue. I'm not using Sync though.

**Comment by sarantsatsral-qy** [comment]
Same issue here.

**Comment by TigBuh99** [comment]
I'm very happy to say that it's fixed now after the latest update.

**Comment by zolrath** [comment]
Yeah, sorry about that! Adding some code to prevent it from wasting bandwidth on links it can't parse and none of the sites I tested with caused CORS errors, will need to expand my test link list!

**Comment by macbikegeek** [comment]
Thanks for this fix. I had the problem and this fixed it. 😄
