### ISSUE TITLE
URL's without `http(s)` or `www` are not detected and transformed

### ISSUE THREAD

**Issue by Gewerd-Strauss** [zolrath/obsidian-auto-link-title#69]
Hello,

assume the following url's:

    http://github.com/gewerd-strauss/
    https://github.com/gewerd-strauss/
    www.github.com/gewerd-strauss/
    https://www.github.com/gewerd-strauss/
    github.com/gewerd-strauss/

These will result in: 

    [Gewerd-Strauss · GitHub](http://github.com/gewerd-strauss/)
    [Gewerd-Strauss · GitHub](https://github.com/gewerd-strauss/)
    [Gewerd-Strauss · GitHub](www.github.com/gewerd-strauss/)
    [Gewerd-Strauss · GitHub](https://www.github.com/gewerd-strauss/)
    github.com/gewerd-strauss/
    
As you can see, url's without an `http(s)` or `www` are not detected.

Is this intended behaviour, and can this be (perhaps optionally) fixed? 

Thank you,
Sincerely,
~Gw

**Comment by thibaultmol** [comment]
Think it might be intentional. it gets complicated to know what a file and what a url is. Definitely now:
[financialstatement.zip](https://financialstatement.zip)

**Comment by zolrath** [comment]
Yep! This is fully intentional and could lead to some fairly unexpected behavior if we tried to parse any possible URLs.
.pizza is a domain in this post .com world.
