### ISSUE TITLE
Doesn't update markdown on page close

### ISSUE THREAD

**Issue by abdulhdr1** [zolrath/obsidian-auto-link-title#74]
Whenever you paste a link and close the page before it completes the fetch data gets lost and the markdown gets stuck in the Fetching state

**Comment by zolrath** [comment]
Hm, this makes sense and I'm not sure I have the ability to do anything about it!
You should be able to trigger the [Overwrite Titles of Existing Links](https://github.com/zolrath/obsidian-auto-link-title#overwrite-titles-of-existing-markdown-links) the next time you open the file!
