### ISSUE TITLE
Maximum title length setting

### ISSUE THREAD

**Issue by silidev** [zolrath/obsidian-auto-link-title#75]
Because some websites missbehave, e. g. Amazon and have very long titles

**Comment by NomarCub** [comment]
#76 has been merged with the [1.5.0](https://github.com/zolrath/obsidian-auto-link-title/releases/tag/1.5.0) release. Can this be closed?

**Comment by zolrath** [comment]
> #76 has been merged with the [1.5.0](https://github.com/zolrath/obsidian-auto-link-title/releases/tag/1.5.0) release. Can this be closed?

Yep, thanks!
