### ISSUE TITLE
[feature request]: Drag & drop of URL

### ISSUE THREAD

**Issue by merlinuwe** [zolrath/obsidian-auto-link-title#79]
Thanks for your great plugin.

I'd suggest to support drag & drop a url to a obsidian note in addition to copy & paste.

**Comment by AndresProgrammer10** [comment]
Yeah, it will be a great feature, Mm any idea for how to do this? Or what way this a should start?

**Comment by zolrath** [comment]
Added in the latest release! 🎉

**Comment by merlinuwe** [comment]
> Added in the latest release! 🎉

Thank you soooo much!
