### ISSUE TITLE
No iOS support for drag and drop

### ISSUE THREAD

**Issue by alx-xlx** [zolrath/obsidian-auto-link-title#95]
The plugin works very well in the desktop version of Obsidian, including windows and macOS. But the plugin doesn't seem to generate any title on the iOS version of the Obsidian when I drag and drop the links onto the obsidian text editor

With external keyboard on iOS the auto generate title works. 

Will **drag and drop-generate title feature** supported in near future ?

**Comment by zolrath** [comment]
I've added drag and drop support in the latest release and have tested it on desktop platforms, can you let me know if it works for you?
Thanks!

**Comment by zolrath** [comment]
No problem, thanks for the report and confirmation! 🔥
