### ISSUE TITLE
Since the author has not merged the request, i fork a copy to handle the relevant requests.

### ISSUE THREAD

**Issue by 3dot141** [zolrath/obsidian-auto-link-title#98]
if author continue maintain this repository, i will create pr

https://github.com/3dot141/obsidian-auto-link-title

> fork https://github.com/khaosdoctor/obsidian-auto-link-title
> because the repository have some updates make the speed of process faster.

> you can use BRAT to direct install this version

- **support direct add link for selection** https://github.com/zolrath/obsidian-auto-link-title/issues/96
![iShot_2023-12-13_10 20 18](https://github.com/zolrath/obsidian-auto-link-title/assets/19152476/50c457e9-0f92-44c0-9641-221d6d1fba19)

- **support custom rules for some websites**
like weixin.qq.com
default like 
<img width="980" alt="image" src="https://github.com/zolrath/obsidian-auto-link-title/assets/19152476/22d453f0-888e-4f75-9910-f5faa38632a0">
but you can customize your rules to get title, like
<img width="524" alt="image" src="https://github.com/zolrath/obsidian-auto-link-title/assets/19152476/a68a6025-eddd-4d87-8771-89c9a11f2e66">

**Comment by zolrath** [comment]
Hello! Sorry for the delay but I'm back to being able to merge and update the plugin!
