### ISSUE TITLE
Pasting links on Android doesn't work after the last update (1.5.0)

### ISSUE THREAD

**Issue by WereWolfPL** [zolrath/obsidian-auto-link-title#99]
After the last update (1.5.0) pasting links doesn't work for me on Android 14.

It seems like it doesn't trigger paste action at all - it doesn't even paste pure link, just nothing. It works fine on windows version.

Previous version (1.4.1) worked fine on my phone.

**Comment by delbian** [comment]
> It seems like it doesn't trigger paste action at all - it doesn't even paste pure link, just nothing. It works fine on windows version.

same problem here

**Comment by zolrath** [comment]
I've moved the new scraper behind an option in Settings.
Seems it works well on desktop but not mobile, more investigation needed but this should let it work on your phone again!

**Comment by WereWolfPL** [comment]
Actually, it didn't help with Android, still doesn't paste anything at all.

I did manage to run developer console for android, here's the error when I try to paste a link to obsidian, maybe it'll help you somehow.
[localhost-1705223419935.log](https://github.com/zolrath/obsidian-auto-link-title/files/13930893/localhost-1705223419935.log)
